@startuml Container
!include <C4/C4_Container>

!include <office/Servers/application_server>
!include <office/Servers/database_server>

/'Users'/
Person(user, "User", "Application user")
Person(admin, "Admin", "Application admin")

/'System'/
System_Boundary(giffter, "Giffter") {
    Container(core, "core", "Container: Java, SpringBoot", "Бэк для приложения")
    Container(bot, "bot", "Container: Java, SpringBoot", "Бэк для пользователей использующих телеграмм бота")
    ContainerDb(db, "db", "Container: Some database", "База в которой храняться пользовательская информация")
    ContainerDb(db1, "db1", "Container: Some database", "База в которой будут храниться данные от клиентов")
}

/'Relations'/

/'Between services'/

/'Between users and services'/

@enduml
